### ISSUE TITLE
.. or not?

### ISSUE THREAD

**Issue by S1SYPHOS** [rosell-dk/webp-realizer#1]
Express yourself! :bug:

**Comment by rosell-dk** [comment]
not what?
not this library?

I guess the [webp-on-demand](https://github.com/rosell-dk/webp-on-demand) approach is most practical in far the most cases. But this library may have its use for some, I guess

**Comment by S1SYPHOS** [comment]
Composer :)

**Comment by rosell-dk** [comment]
ahh :)
Yeah, composer, sure! - In pipeline

**Comment by S1SYPHOS** [comment]
As this project had to stand back, I'll close this issue.

You are doing tremendously important work with your other stuff, and I have but the utmost respect for it.
